#!/usr/bin/env bash
# TODO convert to flake deps
USERJS=$(curl "https://raw.githubusercontent.com/arkenfox/user.js/master/user.js")
echo "# autogenerated by '$0', please do not edit"
echo "{"
echo "$USERJS" \
| rg "user_pref" \
| rg -v "^[ ]*//" \
| rg -v "_user.js.parrot" \
| rg "user_pref\((\"[a-zA-Z0-9\.]+\"),[\s]+(.+)\);.*$" -r '  $1 = $2;'
echo "}"
